trigger:
- main  # Adjust this to the branch you want to trigger the pipeline

variables:
  dockerRegistryServiceConnection: 'MyVotingRegistryConnection'  # Your Docker Registry service connection name
  acrName: 'myVotingRegistry'  # Your ACR name
  imageName: 'myvotingapp'  # Base name for your images

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Images'
  pool:
    vmImage: 'ubuntu-latest'  # Use the hosted agent

  steps:
  - task: Docker@2
    displayName: 'Build and Push Vote Image'
    inputs:
      command: 'buildAndPush'
      containerRegistry: $(dockerRegistryServiceConnection)  # Reference to the Docker Registry service connection
      repository: $(acrName)/vote  # Repository name in ACR
      dockerfile: './vote/Dockerfile'  # Path to the Dockerfile for the vote app
      tags: |
        $(Build.BuildId)  # Tag with the build ID

  - task: Docker@2
    displayName: 'Build and Push Result Image'
    inputs:
      command: 'buildAndPush'
      containerRegistry: $(dockerRegistryServiceConnection)  # Reference to the Docker Registry service connection
      repository: $(acrName)/result  # Repository name in ACR
      dockerfile: './result/Dockerfile'  # Path to the Dockerfile for the result app
      tags: |
        $(Build.BuildId)  # Tag with the build ID

  - task: Docker@2
    displayName: 'Build and Push Worker Image'
    inputs:
      command: 'buildAndPush'
      containerRegistry: $(dockerRegistryServiceConnection)  # Reference to the Docker Registry service connection
      repository: $(acrName)/worker  # Repository name in ACR
      dockerfile: './worker/Dockerfile'  # Path to the Dockerfile for the worker app
      tags: |
        $(Build.BuildId)  # Tag with the build ID

